name: Build

on:
  push:
    branches: [ master, main ]
  schedule:
    # run per hour
    - cron: "0 * * * *"
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if dist branch exists
        id: check_branch
        run: |
          if git ls-remote --heads origin dist | grep dist; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Download previous dist files
        if: steps.check_branch.outputs.exists == 'true'
        uses: actions/checkout@v4
        with:
          ref: dist
          path: dist

      - name: Create dist directory if it doesn't exist
        if: steps.check_branch.outputs.exists == 'false'
        run: mkdir -p dist

      - name: Generate badges
        shell: bash
        run: timeout 3m python -u main.py --author '${{ secrets.AUTHOR }}' --scholar='${{ secrets.SCHOLAR }}' --wos '${{ secrets.WOS }}' --gen_summary

      - name: Adding summary
        run: cat summary.md >> $GITHUB_STEP_SUMMARY

      - name: Configure Git
        run: |
          rm -rf .git
          rm -rf dist/.git
          cd dist
          
          # Create CNAME file if the secret is provided
          if [ ! -z "${{ secrets.CNAME }}" ]; then
            echo "${{ secrets.CNAME }}" > CNAME
          fi
          
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update badges"
          
          # Use the repository that triggered the workflow
          REPO_URL="https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git"
          git remote add origin $REPO_URL

      - name: Push to dist branch
        uses: ad-m/github-push-action@master
        with:
          branch: dist
          force: true
          directory: dist
